services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: userpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    image: api-technova:v1
    container_name: flask_api
    restart: always
    ports:
      - "5050:5050"
    environment:
      DB_HOST: db
      DB_USER: user_app
      DB_PASS: userpass
      DB_NAME: app_db
      FLASK_DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5050/health')"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  db_data: