version: '3.8'

services:
  # 1. Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: userpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  # 2. Aplicacion Flask API
  web:
    build: .
    image: api-technova:v1
    container_name: flask_api
    restart: always
    ports:
      - "5050:5050"
    environment:
      DB_HOST: db
      DB_USER: user_app
      DB_PASS: userpass
      DB_NAME: app_db
      FLASK_DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5050/health')"]
      interval: 15s
      timeout: 5s
      retries: 5

  # 3. Nginx Proxy Manager (Gestor de Trafico 80, 443 y Panel 81)
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  # 4. Dozzle (Visualizador de logs en tiempo real)
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle_logs
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  # 5. Uptime Kuma (Monitor de estado de servicios)
  kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - ./kuma-data:/app/data
    restart: always

volumes:
  db_data: