name: CI/CD Pipeline - Technova API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit

      - name: 1. Pruebas unitarias con Pytest
        run: |
          pytest test_app.py

      - name: 2. Auditoría de código estático con Bandit
        run: |
          bandit -r . -x ./venv,./test_app.py -f txt -o resultado_bandit.txt

      - name: Subir reporte de Bandit como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-bandit
          path: resultado_bandit.txt

      - name: Construir imagen Docker
        run: |
          docker build -t api-technova:latest .

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Clonar repositorio para escaneo
        uses: actions/checkout@v4

      - name: Construir imagen local para auditoría
        run: |
          docker build -t api-technova:latest .

      - name: 3. Escaneo de vulnerabilidades en contenedor con Trivy (Bloqueante)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'api-technova:latest'
          format: 'table'
          output: 'trivy-report.txt'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          trivyignores: '.trivyignore'

      - name: Subir reporte de Trivy como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-trivy
          path: trivy-report.txt

      - name: Ejecutar despliegue vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/evidencia2-sena/ejercicio-docker-audit-sai || exit
            git pull origin main
            docker compose down
            docker compose up -d --build